/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface WcThree {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface WcThreeAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'WcThree': Components.WcThree;
  }

  interface StencilIntrinsicElements {
    'wc-three': Components.WcThreeAttributes;
  }


  interface HTMLWcThreeElement extends Components.WcThree, HTMLStencilElement {}
  var HTMLWcThreeElement: {
    prototype: HTMLWcThreeElement;
    new (): HTMLWcThreeElement;
  };

  interface HTMLElementTagNameMap {
    'wc-three': HTMLWcThreeElement
  }

  interface ElementTagNameMap {
    'wc-three': HTMLWcThreeElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
