/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface WcTwo {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLWcTwoElement extends Components.WcTwo, HTMLStencilElement {}
  var HTMLWcTwoElement: {
    prototype: HTMLWcTwoElement;
    new (): HTMLWcTwoElement;
  };
  interface HTMLElementTagNameMap {
    'wc-two': HTMLWcTwoElement;
  }
}

declare namespace LocalJSX {
  interface WcTwo {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'wc-two': WcTwo;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'wc-two': LocalJSX.WcTwo & JSXBase.HTMLAttributes<HTMLWcTwoElement>;
    }
  }
}


