/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface WcOne {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface WcOneAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'WcOne': Components.WcOne;
  }

  interface StencilIntrinsicElements {
    'wc-one': Components.WcOneAttributes;
  }


  interface HTMLWcOneElement extends Components.WcOne, HTMLStencilElement {}
  var HTMLWcOneElement: {
    prototype: HTMLWcOneElement;
    new (): HTMLWcOneElement;
  };

  interface HTMLElementTagNameMap {
    'wc-one': HTMLWcOneElement
  }

  interface ElementTagNameMap {
    'wc-one': HTMLWcOneElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
